PayAuthService: 
  Db:
    LogsConnString:
      settings-key: PayAuthService-LogsConnString
      types: [ AzureTableStorage, Tag ]
    DataConnString: 
      settings-key: PayAuthService-DataConnString
      types: [ AzureTableStorage, Tag ]
  ResetPasswordAccessTokenExpiration:
    settings-key: PayAuthService-ResetPasswordAccessTokenExpiration
  Cqrs:
    RabbitMqConnectionString:
      settings-key: SagasRabbitMqConnStr
      types: [RabbitMq]
    ChaosKitty:
      StateOfChaos: 0.2
  ResetPasswordUrlTemplate:
    settings-key: LykkePayResetPasswordUrlTemplate
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [AzureTableStorage]
    QueueName: slack-notifications
  ThrottlingLimitSeconds:
    settings-key: SlackNotificationsThrottlingLimit
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl