PayAuthService: 
  Db:
    LogsConnString:
      settings-key: LykkePayLogsConnString
      types: [ AzureTableStorage, Tag ]
    DataConnString: 
      settings-key: LykkePayDataConnString
      types: [ AzureTableStorage, Tag ]
  ResetPasswordAccessTokenExpiration:
    settings-key: PayAuthService-ResetPasswordAccessTokenExpiration
    types: [ Tag ]
  Cqrs:
    RabbitMqConnectionString:
      settings-key: RabbitSagas
      types: [ RabbitMq, Tag ]
    ChaosKitty:
      StateOfChaos: 0.2
  ResetPasswordUrlTemplate:
    settings-key: LykkePayResetPasswordUrlTemplate
    types: [ Tag ]
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [AzureTableStorage]
    QueueName: slack-notifications
  ThrottlingLimitSeconds:
    settings-key: SlackNotificationsThrottlingLimit
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
    types: [ Tag ]